1.

In [1]:
import numpy as np

def is_safe(board, row, col, n):
    # Check this 
    for i in range(row):
        if board[i][col] == 1:
            return False
    
    # Check upper left diagonal
    for i, j in zip(range(row, -1, -1), range(col, -1, -1)):
        if board[i][j] == 1:
            return False
    
    # Check upper right diagonal
    for i, j in zip(range(row, -1, -1), range(col, n, 1)):
        if board[i][j] == 1:
            return False
    
    return True

def solve_n_queens(board, row, n):
    if row >= n:
        return True
    
    for col in range(n):
        if is_safe(board, row, col, n):
            board[row][col] = 1
            if solve_n_queens(board, row + 1, n):
                return True
            board[row][col] = 0  # Backtrack
    
    return False

def n_queens(n=8):
    board = np.zeros((n, n), dtype=int)
    if solve_n_queens(board, 0, n):
        return board
    else:
        return "No solution exists"

# Run the function and print the solution
solution = n_queens(8)
print(solution)


[[1 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]]


3.

In [ ]:
import numpy as np

def generate_magic_square(n):
    if n % 2 == 1:  # Odd-order magic square using Siamese method
        magic_square = np.zeros((n, n), dtype=int)
        i, j = 0, n // 2
        for num in range(1, n * n + 1):
            magic_square[i, j] = num
            new_i, new_j = (i - 1) % n, (j + 1) % n
            if magic_square[new_i, new_j]:
                i += 1
            else:
                i, j = new_i, new_j
    
    elif n % 4 == 0:  # Doubly Even Order Magic Square
        magic_square = np.arange(1, n * n + 1).reshape(n, n)
        mask = np.array([(i % 4 == j % 4 or (i + j) % 4 == 3) for i in range(n) for j in range(n)]).reshape(n, n)
        magic_square[mask], magic_square[~mask] = magic_square[~mask], magic_square[mask]
    
    else:  # Singly Even Order Magic Square (4k+2)
        half_n = n // 2
        sub_square_size = half_n * half_n
        sub_square = generate_magic_square(half_n)
        magic_square = np.zeros((n, n), dtype=int)
        
        for i in range(2):
            for j in range(2):
                magic_square[i * half_n:(i + 1) * half_n, j * half_n:(j + 1) * half_n] = sub_square + sub_square_size * (i * 2 + j)
        
        k = (n - 2) // 4
        cols1 = list(range(k)) + list(range(n - k, n))
        cols2 = [k]
        
        magic_square[:half_n, cols1], magic_square[half_n:, cols1] = magic_square[half_n:, cols1], magic_square[:half_n, cols1]
        magic_square[:half_n, cols2], magic_square[half_n:, cols2] = magic_square[half_n:, cols2], magic_square[:half_n, cols2]
    
    return magic_square

# Test for different values of N
for n in range(4, 9):
    print(f"Magic Square for N={n}:")
    print(generate_magic_square(n))
    print("\n")


4.

In [ ]:
import numpy as np

# Set N (N >= 10)
N = 10  # You can increase this value

# Generate N random points (x, y) in range [-10, 10]
cartesian_points = np.random.uniform(-10, 10, (N, 2))

# Convert Cartesian to Polar coordinates
r = np.sqrt(cartesian_points[:, 0]**2 + cartesian_points[:, 1]**2)
theta = np.arctan2(cartesian_points[:, 1], cartesian_points[:, 0])  # arctan2 handles quadrants

# Store polar coordinates in an array
polar_points = np.column_stack((r, theta))

# Display the results
print("Cartesian Coordinates (x, y):")
print(cartesian_points)
print("\nPolar Coordinates (r, θ in radians):")
print(polar_points)


5.

In [ ]:
import numpy as np

# Sample NumPy array with strings
arr = np.array(["Hello", "NumPy", "Python", "AI", "Code"])

# Function to format elements with padding
def format_strings(arr):
    centered = np.array([s.center(15, '_') for s in arr])
    left_justified = np.array([s.ljust(15, '_') for s in arr])
    right_justified = np.array([s.rjust(15, '_') for s in arr])
    
    return centered, left_justified, right_justified

# Apply formatting
centered, left_justified, right_justified = format_strings(arr)

# Display results
print("Centered Strings:")
print(centered)

print("\nLeft-Justified Strings:")
print(left_justified)

print("\nRight-Justified Strings:")
print(right_justified)


6.

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# Function to evaluate the polynomial (user input)
def f(x):
    # User can input the polynomial as a string, and eval can interpret it
    return eval(poly_expr)

# Take user input for the polynomial function
print("Enter the polynomial function in terms of x, e.g., 'x**3 - 4*x - 9'")
poly_expr = input("Polynomial f(x): ")

# Take user input for the interval [a, b]
a = float(input("Enter the starting point 'a' for the interval: "))
b = float(input("Enter the ending point 'b' for the interval: "))

# Ensure f(a) * f(b) < 0, i.e., the function has different signs at the interval bounds
if f(a) * f(b) > 0:
    print("Invalid interval. f(a) and f(b) must have opposite signs.")
else:
    # Bisection Method parameters
    tolerance = float(input("Enter the tolerance level (e.g., 1e-6): "))
    max_iterations = int(input("Enter the maximum number of iterations: "))

    iterations = []
    midpoints = []

    # Perform the Bisection Method
    for _ in range(max_iterations):
        midpoint = (a + b) / 2
        iterations.append([a, midpoint, b])  # Store the interval
        midpoints.append(midpoint)  # Store the midpoint values

        if abs(f(midpoint)) < tolerance:
            break  # Stop when the root is found

        if f(a) * f(midpoint) < 0:
            b = midpoint
        else:
            a = midpoint

    # Convert to a NumPy array
    iterations = np.array(iterations)

    # Plot root-finding process
    x_values = np.linspace(a-1, b+1, 400)  # To plot over the current interval
    y_values = f(x_values)

    plt.figure(figsize=(8, 5))
    plt.plot(x_values, y_values, label=f"f(x) = {poly_expr}")
    plt.axhline(0, color="black", linestyle="--")

    # Plot the midpoint iterations
    plt.scatter(midpoints, f(np.array(midpoints)), color="red", label="Midpoints (Iterations)", marker="o")

    plt.xlabel("x")
    plt.ylabel("f(x)")
    plt.title("Bisection Method Root Finding")
    plt.legend()
    plt.grid()
    plt.show()

    # Display final root
    root = midpoints[-1]
    print(f"Approximate root: {root:.6f}")
    print("Bisection intervals stored in NumPy array:\n", iterations)
